n = int(input('Digite uma número para ver a sua tabuada :'))
print('-' * 12)
print('{} X 01 = {}'.format(n, (n * 1)))
print('{} X 02 = {}'.format(n, (n * 2)))
print('{} X 03 = {}'.format(n, (n * 3)))
print('{} X 04 = {}'.format(n, (n * 4)))
print('{} X 05 = {}'.format(n, (n * 5)))
print('{} X 06 = {}'.format(n, (n * 6)))
print('{} X 07 = {}'.format(n, (n * 7)))
print('{} X 08 = {}'.format(n, (n * 8)))
print('{} X 09 = {}'.format(n, (n * 9)))
print('{} X 10 = {}'.format(n, (n * 10)))
print('-' * 12)